receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  # prometheus:
  #   endpoint: "0.0.0.0:1234"
  # otlp:
  #   endpoint: tempo:4007
    # tls:
    #   insecure: true
  loki:
    endpoint: http://loki-service:3100/loki/api/v1/push
  # zipkin:
  #   endpoint: http://zipkin:9411/api/v2/spans

extensions:
  # health_check:
  # zpages:
  #    endpoint: otel-collector:55679

processors:
  # Data sources: traces, metrics, logs
  batch:

service:
  # extensions: [zpages, health_check]
  pipelines:
    # # metrics:
    # #   receivers: [otlp]
    # #   exporters: [prometheus]
    # traces:
    #   receivers: [otlp]
    #   # processors: [batch]
    #   exporters: [zipkin]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]